INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('AppleStore官方旗舰店', 'MacBookAir笔记本', 7399.00, 401, 5899.00, '笔记本电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('AppleStore官方旗舰店', 'iPad Pro', 13099.00, 550, 8099.00, '平板电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('AppleStore官方旗舰店', 'iPad mini', 5065.00, 344, 3500.00, '平板电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('AppleStore官方旗舰店', 'iPhone 11 Pro', 11799.00, 560, 6899.00, '智能手机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('YAMAHA官方旗舰店', '雅马哈民谣木吉他f310', 899.00, 5486, 434.00, '乐器');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('YAMAHA官方旗舰店', '雅马哈电子钢琴P48B', 2677.00, 4813, 2500.00, '乐器');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('三只松鼠旗舰店', '三只松鼠手撕面包', 30.00, 12341, 20.00, '美食');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('三只松鼠旗舰店', '三只松鼠韩国进口火鸡面', 29.00, 1628, 21.00, '美食');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('三只松鼠旗舰店', '混合果仁零食大礼包', 280.00, 4709, 190.00, '美食');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('任天堂官方旗舰店', '掌机NS体感游戏机', 2799.00, 3913, 1999.00, '游戏');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('佳能官方旗舰店', '佳能EOS5D单反相机', 19149.00, 18, 16329.00, '相机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('全友家居官方旗舰店', '单人多功能沙发躺椅', 1499.00, 9951, 999.00, '家具');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('力士官方旗舰店', 'LUX补水大白瓶洗护套装', 70.00, 3404, 45.00, '洗护');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('华为官方旗舰店', 'HUAWEI MatePad Pro', 6799.00, 991, 5099.00, '平板电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('华为官方旗舰店', 'HUAWEI P40 Pro', 5988.00, 15688, 5199.00, '智能手机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('华为官方旗舰店', 'HUAWEI nova7 SE', 2399.00, 16108, 1699.00, '智能手机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('大诚网友专营店', '100Q币充值', 100.00, 9999, 100.00, '游戏');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('大诚网友专营店', '英雄联盟游戏代练', 50.00, 9999, 35.00, '游戏');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('小米官方旗舰店', '小米10智能手机', 3799.00, 9133, 3099.00, '智能手机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('小米官方旗舰店', '小米游戏笔记本2019新款', 8499.00, 20, 7599.00, '笔记本电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('尼康官方旗舰店', '尼康D5600入门级单反相机', 3899.00, 123, 2600.00, '相机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('得力官方旗舰店', 'S90金属宝珠笔子弹头', 50.00, 69, 45.00, '学习用品');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('得力官方旗舰店', '海外Explora卡通直尺', 4.00, 882, 3.00, '学习用品');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('惠普官方旗舰店', '惠普暗影精灵5', 6099.00, 1175, 4199.00, '笔记本电脑');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('木马人家具旗舰店', '厨房置物架落地多层架', 499.00, 9988, 300.00, '家具');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('波司登官方旗舰店', '新款时尚保暖羽绒服', 1379.00, 799, 227.00, '秋冬服装');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '云南金银水果玉米', 30.00, 9921, 21.00, '蔬菜');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '山东烟台美早大樱桃', 50.00, 4885, 38.00, '水果');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '山东紫皮大蒜', 22.00, 1878, 16.00, '蔬菜');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '新鲜宜昌小土豆', 20.00, 298, 16.00, '蔬菜');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '水果黄瓜', 20.00, 2808, 10.00, '蔬菜');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '海南台农芒果', 28.00, 411, 19.00, '水果');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('王小二旗舰店', '湖北黄肉黑布林', 30.00, 77951, 22.00, '水果');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('索尼官方旗舰店', '索尼Alpha7IIIA7M3', 14199.00, 190, 8999.00, '相机');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('美特斯邦威', '牛仔夹克复古女外套', 60.00, 4, 45.00, '秋冬服装');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('美特斯邦威', '韩版时尚ins连帽夹克', 56.00, 2465, 42.00, '秋冬服装');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('骆驼户外官方旗舰店', '户外露营加厚双人睡袋', 78.00, 34598, 51.00, '户外');
INSERT INTO `t_goods`(`busName`, `goodsName`, `goodsPrice`, `goodsNum`, `goodsOriginalPrice`, `type`) VALUES ('骆驼户外官方旗舰店', '星空液压野外帐篷', 349.00, 1114, 269.00, '户外');
